version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: orderflow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderflow
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: orderflow-auth
    ports:
      - "8081:8081"
    environment:
      - DB_DSN=postgres://postgres:postgres@postgres:5432/orderflow?sslmode=disable
      - JWT_SECRET=shared-secret-123
      - PORT=8081
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build: ./order-service
    container_name: orderflow-order
    ports:
      - "8082:8082"
    environment:
      - DB_DSN=postgres://postgres:postgres@postgres:5432/orderflow?sslmode=disable
      - JWT_SECRET=shared-secret-123
      - PORT=8082
    depends_on:
      postgres:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    container_name: orderflow-notifier
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - QUEUE_NAME=order.created
    depends_on:
      rabbitmq:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: orderflow-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: orderflow-rabbitmq
    ports:
      - "5672:5672"   # AMQP протокол
      - "15672:15672" # Web UI (логин/пароль: guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data: